### ISSUE TITLE
Hide inactive endpoints

### ISSUE THREAD

**Issue by BFergerson** [sourceplusplus/sourceplusplus#1021]
![image](https://github.com/sourceplusplus/sourceplusplus/assets/3278877/54edd051-f621-4db4-95f6-60272f45d0d2)

**Comment by chess-equality** [comment]
Not yet started.

**Comment by chess-equality** [comment]
In progress.

**Comment by chess-equality** [comment]
I believe I need to deploy my changes to a development sandbox of Source++ Platform (`platform-up` in Gradle?) and connect the JetBrains Plugin to it?

**Comment by BFergerson** [comment]
`platform-up` will boot your local platform, `plugin-run` will boot your local plugin. You can then add a `.spp/spp-plugin.yml` file with the following:
```yaml
override: true
service_host: "http://localhost"
authorization_code: "change-me"
service_name: "demo-java"
```

That will point it to your local platform. You can open the `demo-java` application if you want to use that. You can just run that application and it'll connect locally.
