### ISSUE TITLE
Displaying live charts over 4 hours fails

### ISSUE THREAD

**Issue by BFergerson** [sourceplusplus/sourceplusplus#1041]
Example:
![live-activity-chart-fail](https://github.com/sourceplusplus/sourceplusplus/assets/3278877/935b306b-6182-40e8-ba44-c090415eca36)

Chart is generated by `LiveViewChartWindow`. Metrics can be fetched with `spp-plugin.yml` of:
```yaml
override: true
service_host: "https://tenant1.sourceplus.plus"
authorization_code: "openmma-auth"
service_name: "openmma"
```
