### ISSUE TITLE
Ability to create/assign developers & roles in spp-platform.yml

### ISSUE THREAD

**Issue by BFergerson** [sourceplusplus/sourceplusplus#749]
There is currently do way to create developers and assign roles/redactions/access permissiosn via a configuration file. They must be done via API.

Should have something like:
```yml
roles:
    - id: "test-role"
      permissions: ["ADD_BREAKPOINT"]
developers:
    - id: "test-developer"
      accessToken: "test-token"
developer_roles:
    - id: "test-developer"
      role: "test-role"
```
